Repository kubewarden/policy-server, pull requests merged in 2022-10, with the labels that each got.

#329 Change architecture of Workers pool
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/communication.rs
  src/main.rs
  src/policy_downloader.rs
  src/settings.rs
  src/utils.rs
  src/worker.rs
  src/worker_pool.rs
Labels: bug, enhancement

#343 update deps
  Cargo.lock
  Cargo.toml
  src/cli.rs
  src/main.rs
Labels: enhancement

#353 chore: tell dependabot to look after github actions
  .github/dependabot.yml
Labels: enhancement

#355 Artifacthub and OpenSSF badges
  README.md
Labels: documentation, enhancement
