Repository kubewarden/policy-server, pull requests merged in 2023-09, with the labels that each got.

#536 chore(deps): be explicit about GH action version
  .github/workflows/ci.yml
  .github/workflows/container-image.yml
  .github/workflows/fossa.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/sbom.yml
  .github/workflows/security-audit-cron.yml
  .github/workflows/security-audit-reactive.yml
  .github/workflows/sign-image.yml
Labels: area/dependencies, kind/chore

#542 build(deps): update opentelemetry
  Cargo.lock
  Cargo.toml
  DEVELOPMENT.md
  policies.yml.example
  src/metrics/mod.rs
  src/metrics/policy_evaluations_latency.rs
Labels: area/dependencies

#546 docs: simplify development guide by using docker-compose
  DEVELOPMENT.md
  hack/docker-compose.yml
  hack/grafana-datasources.yml
  hack/otel-collector-minimal-config.yml
  hack/prometheus.yml
  prometheus.yml
Labels: area/documentation, kind/chore
