Repository kubewarden/policy-server, pull requests merged in 2023-11, with the labels that each got.

#595 fix: use async Mutext
  src/policy_downloader.rs
Labels: kind/bug

#598 build(deps): bump policy-evaluator to v0.12.2
  Cargo.lock
  Cargo.toml
  src/settings.rs
Labels: area/dependencies

#600 feat: Add new `request_origin` to metrics baggage
  src/communication.rs
  src/metrics/mod.rs
  src/worker.rs
Labels: kind/feature

#602 feat: Expand grafana dashboard, bump to schemaVersion 38
  kubewarden-dashboard.json
Labels: kind/feature
