Repository kubewarden/policy-server, pull requests merged in 2023-01, with the labels that each got.

#396 Revert "feat: policy timeout protection"
  .github/workflows/tests.yml
  Cargo.lock
  Cargo.toml
  Makefile
  e2e-tests/.gitignore
  e2e-tests/01-setup.yml
  e2e-tests/02-monitor-and-protect-modes.yml
  e2e-tests/03-audit-endpoint.yml
  e2e-tests/04-timeout-protection.yml
  e2e-tests/99-teardown.yml
  e2e-tests/Makefile
  e2e-tests/e2e-tests-policies/.gitignore
  e2e-tests/test_data/pod_sleep_100ms.json
  e2e-tests/test_data/pod_sleep_4s.json
  e2e-tests/test_data/pod_with_privileged_containers.json
  e2e-tests/test_data/policies.yaml
  src/cli.rs
  src/main.rs
  src/worker.rs
  src/worker_pool.rs
Labels: kind/feature

#392 Trigger Helm chart release.
  .github/workflows/release.yml
Labels: release/skip-changelog, area/ci

#402 Fix release drafter autolabeler and exclude-labels.
  .github/release-drafter.yml
Labels: kind/bug, release/skip-changelog, area/ci

#403 fix airgap links
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#407 chore: ignore twoway warning
  .cargo/audit.toml
Labels: kind/chore
