Repository kubewarden/policy-server, pull requests merged in 2023-10, with the labels that each got.

#560 chore: bump otel collector dev container to 0.85.0
  .gitignore
  hack/docker-compose.yml
  hack/otel-collector-minimal-config.yml
Labels: area/dependencies, kind/chore

#571 feat(docs): code convention section
  CONTRIBUTING.md
Labels: kind/feature

#567 feat: raw policy validation
  Cargo.lock
  Cargo.toml
  e2e-tests/07-raw-policies.yml
  e2e-tests/test_data/policies.yaml
  e2e-tests/test_data/raw_mutation.json
  e2e-tests/test_data/raw_validation.json
  src/admission_review.rs
  src/api/audit_and_validation.rs
  src/api/mod.rs
  src/communication.rs
  src/main.rs
  src/metrics/mod.rs
  src/metrics/policy_evaluations_latency.rs
  src/metrics/policy_evaluations_total.rs
  src/policy_downloader.rs
  src/raw_review.rs
  src/server.rs
  src/settings.rs
  src/worker.rs
  src/worker_pool.rs
Labels: kind/feature

#572 chore: bump version to v1.9.0-rc1
  Cargo.lock
  Cargo.toml
Labels: kind/chore
