Repository kubewarden/policy-server, pull requests merged in 2024-03, with the labels that each got.

#689 chore: bump version to v1.11.0-rc2
  Cargo.toml
Labels: kind/chore

#690 chore: update Cargo.lock
  Cargo.lock
Labels: kind/chore

#693 add pprof support
  Cargo.lock
  Cargo.toml
  src/api/handlers.rs
  src/cli.rs
  src/config.rs
  src/lib.rs
  src/profiling.rs
  tests/common/mod.rs
Labels: kind/enhancement

#694 build(deps): bump policy-evaluator version to v0.16.2
  Cargo.lock
  Cargo.toml
Labels: area/dependencies

#695 chore: bumps version in Cargo.toml to v1.11.0-rc3.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#701 chore: use tarpaulin-install action to install tarpaulin.
  .github/workflows/ci.yml
Labels: kind/chore

#702 fix(ci): set prerelease and latest flag properly.
  .github/workflows/release.yml
Labels: kind/bug

#705 chore: bump v1.11.0-rc5.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#715 chore: bump v1.11 version.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#712 feat: do not exit on policy error
  src/api/service.rs
  src/evaluation/errors.rs
  src/evaluation/evaluation_environment.rs
  src/evaluation/precompiled_policy.rs
  src/lib.rs
  src/policy_downloader.rs
  tests/common/mod.rs
  tests/integration_test.rs
Labels: kind/enhancement, kind/feature

#713 feat: add policy initialization error metric
  src/api/service.rs
  src/metrics.rs
Labels: area/observability, kind/feature
