Repository kubewarden/policy-server, pull requests merged in 2024-05, with the labels that each got.

#766 feat: switch to jemalloc allocator
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: kind/feature

#767 build(deps): bump policy-evaluator version to v0.17.2
  Cargo.lock
  Cargo.toml
Labels: area/dependencies

#769 chore(deps): change GH action used by cargo-audit
  .github/workflows/security-audit-cron.yml
  .github/workflows/security-audit-reactive.yml
Labels: area/dependencies, kind/chore

#770 fix: configure jemalloc in lib.rs
  src/lib.rs
  src/main.rs
  tests/common/mod.rs
Labels: kind/bug

#773 test: fix permissions of cargo audit action
  .github/workflows/security-audit-cron.yml
  .github/workflows/security-audit-reactive.yml
Labels: kind/bug

#776 fix: disable readiness probe handler logs
  src/lib.rs
Labels: kind/bug

#784 chore: add Kubewarden repository badges.
  README.md
Labels: kind/chore
