Repository kubewarden/policy-server, pull requests merged in 2024-07, with the labels that each got.

#814 feat: introduce group policies
  Cargo.lock
  Cargo.toml
  README.md
  policies.yml.example
  src/api/handlers.rs
  src/api/service.rs
  src/api/state.rs
  src/config.rs
  src/evaluation.rs
  src/evaluation/errors.rs
  src/evaluation/evaluation_environment.rs
  src/evaluation/policy_evaluation_settings.rs
  src/evaluation/policy_id.rs
  src/lib.rs
  src/policy_downloader.rs
  tests/common/mod.rs
  tests/data/gatekeeper_always_happy_policy.wasm
  tests/data/pod_without_privileged_containers.json
  tests/integration_test.rs
Labels: kind/feature

#827 fix policies yml parsing
  policies.yml.example
  src/config.rs
Labels: kind/bug

#826 feat: automatic TLS certificate reload
  Cargo.lock
  Cargo.toml
  src/lib.rs
  tests/integration_test.rs
Labels: kind/feature

#835 chore(deps): bump OpenTelemetry version to 0.24.
  Cargo.lock
  Cargo.toml
  src/tracing.rs
Labels: area/dependencies, kind/chore

#842 chore: bump v1.15.0-rc1.
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#843 fix: policies.yml parsing
  src/config.rs
Labels: kind/bug

#848 fix: call set_meter_provider
  hack/docker-compose.yml
  src/metrics.rs
Labels: kind/bug
