Repository kubewarden/policy-server, pull requests merged in 2024-09, with the labels that each got.

#895 fix: address changes to Sigstore's TUF repository
  Cargo.lock
  Cargo.toml
Labels: kind/bug, area/dependencies, kind/chore

#898 chore: update cargo audit ignore list
  .cargo/audit.toml
Labels: kind/chore

#904 chore: prepare to release v1.17.0-rc2
  Cargo.lock
  Cargo.toml
Labels: kind/chore

#908 group policy: improve evaluation response
  src/evaluation/evaluation_environment.rs
  tests/data/gatekeeper_always_unhappy_policy.wasm
Labels: kind/enhancement

#909 fix: revisit AdmissionResponse of policy groups
  Cargo.lock
  Cargo.toml
  src/api/service.rs
  src/evaluation/evaluation_environment.rs
  tests/integration_test.rs
Labels: kind/bug

#913 fix: make cert rotation detection more reliable
  Cargo.toml
  src/lib.rs
  tests/integration_test.rs
Labels: kind/bug

#925 test: add json output as otel assertions custom message
  tests/integration_test.rs
Labels: kind/tech-debt

#928 fix: remove warnings from policy groups.
  src/evaluation/evaluation_environment.rs
  tests/integration_test.rs
Labels: kind/bug

#932 chore(deps): bump policy-evaluator
  Cargo.lock
  Cargo.toml
Labels: area/dependencies, kind/chore
