Repository kubewarden/policy-server, pull requests merged in 2024-08, with the labels that each got.

#859 test: add otelc integration test
  Cargo.lock
  Cargo.toml
  Makefile
  tests/common/mod.rs
  tests/data/otel-collector-config.yaml
  tests/integration_test.rs
Labels: kind/tech-debt

#863 fix: properly configure rustls stack
  Cargo.lock
  Cargo.toml
  src/main.rs
  tests/integration_test.rs
Labels: kind/bug

#872 chore: Rename SECURITY-INSIGHTS.yml for CLOMonitor
  SECURITY-INSIGHTS.yml
Labels: kind/chore

#874 fix: allow Docker image to be built locally
  Dockerfile
Labels: kind/bug

#877 fix(ci): container build permissions in release workflow.
  .github/workflows/release.yml
Labels: kind/bug
