Repository kubewarden/policy-server, pull requests merged in 2025-01, with the labels that each got.

#1016 fix!: renames "url" field into "module".
  README.md
  policies.yml.example
  src/config.rs
  src/evaluation/evaluation_environment.rs
  src/policy_downloader.rs
  tests/common/mod.rs
  tests/integration_test.rs
Labels: kind/bug, kind/breaking-change

#1029 chore(ci): use common renovate bot configuration.
  renovate.json
Labels: kind/chore

#1036 build(deps): bump jemalloc crates.
  Cargo.lock
  Cargo.toml
Labels: area/dependencies

#1047 fix: cargo install ignoring Cargo.lock
  Dockerfile
Labels: kind/bug, area/ci

#1056 feat(cli): generate CLI reference documentation.
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  Makefile
  README.md
  cli-docs.md
  src/cli.rs
  src/main.rs
Labels: kind/feature
