Repository kubewarden/policy-server, pull requests merged in 2025-05, with the labels that each got.

#1173 chore(deps): add rust-toolchain.toml.
  .github/workflows/ci.yml
  .github/workflows/update-rust-toolchain.yaml
  rust-toolchain.toml
  updatecli/DEVELOP.md
  updatecli/updatecli.d/update-rust-toolchain.yaml
  updatecli/values.yaml
Labels: kind/chore, area/dependencies

#1176 fix: add missing rust toolchain targets.
  rust-toolchain.toml
Labels: kind/bug

#1166 feat: check ```protocol_version``` before storing
  src/evaluation/precompiled_policy.rs
Labels: kind/feature
