Repository kubewarden/policy-server, pull requests merged in 2025-02, with the labels that each got.

#1070 fix: address broken sigstore's TUF repository
  Cargo.lock
  Cargo.toml
Labels: kind/bug

#1071 fix: do not panic in certificate hot-reload task
  src/lib.rs
Labels: kind/bug, area/certificates

#1073 chore(deps): update sigstore
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#1084 build(deps): remove dependabot.
  .github/dependabot.yml
Labels: area/dependencies

#1075 feat: enable mTLS.
  Cargo.lock
  Cargo.toml
  cli-docs.md
  src/cli.rs
  src/config.rs
  src/lib.rs
  tests/integration_test.rs
Labels: kind/feature

#1080 feat: expose readiness probe over http
  cli-docs.md
  src/cli.rs
  src/config.rs
  src/lib.rs
  tests/common/mod.rs
  tests/integration_test.rs
Labels: kind/feature, area/certificates

#1087 fix: TlsConfig and mTLS logic
  cli-docs.md
  src/cli.rs
  src/config.rs
  src/lib.rs
  tests/integration_test.rs
Labels: kind/bug

#1089 chore(deps): update policy-evaluator
  .taplo.toml
  Cargo.lock
  Cargo.toml
Labels: kind/chore, area/dependencies

#1090 feat: multiple client CA.
  src/cli.rs
  src/config.rs
  src/lib.rs
  tests/integration_test.rs
Labels: kind/feature

#1094 fix: remove TLS hot-reload race condition
  src/certs.rs
  src/config.rs
  src/lib.rs
  tests/integration_test.rs
Labels: kind/bug

#1096 fix: clap cannot downcast CLI flags to PathBuf
  src/cli.rs
Labels: kind/bug

#1099 chore(build): Update OTEL
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/metrics.rs
  src/tracing.rs
  tests/data/otel-collector-config.yaml
  tests/integration_test.rs
Labels: kind/chore
